### ISSUE TITLE
shiftZone function

### ISSUE THREAD

**Issue by Hermanverschooten** [justinmimbs/time-extra#8]
Would it be possible to add a function to shift the posix time from one time zone to another?

I have `Time.Posix` value that is in local time and I need to shift it to UTC.

**Comment by justinmimbs** [comment]
Hi Herman,

If you know the offset (or can extract it with `toOffset`), then you could use the `add` function to shift your time. 

Another way could be to use `posixToParts utc` to extract the local time parts, and then convert those parts to UTC with `partsToPosix localZone`.

```elm
time = 
    naiveTime |> posixToParts utc |> partsToPosix localZone
```

Does that help? If not, then if you describe your case in more detail perhaps I can help.

Thanks,

Justin

**Comment by Hermanverschooten** [comment]
Hey Justin,

I currently did it in the first way with `add`, don't know if which way is best though.

I just thought as this is a common thing, it would be nice to have it as a function.

Thanks,

Herman

**Comment by justinmimbs** [comment]
Thanks, Herman. I'm reluctant to add such a function, as I don't know if it's worth the cost of expanding the API. There are already a few succinct ways to write it, and I don't know how common it is. So I'll look out for it to be brought up again.

Thanks,

Justin
