### ISSUE TITLE
expose posixFromDateTime ?

### ISSUE THREAD

**Issue by jweir** [justinmimbs/time-extra#9]
We are needing to convert Dates to Posix values at the start of a local date.  `posixFromDateTime` should work perfect for our needs, so I wondered if there was any chance of exposing it?

Thank you!

**Comment by justinmimbs** [comment]
Hi John,

Thanks for asking! I'm not in favor of exposing it because I'd rather this library not introduce the `Date` type and another representation of clock time (in milliseconds).

Is the function you want something that can be defined like this?

```elm
dateToPosix zone d =
    Parts (Date.year d) (Date.month d) (Date.day d) 0 0 0 0
        |> partsToPosix zone
```

Thanks,

Justin

**Comment by jweir** [comment]
This is a perfectly acceptable solution.  Thank you very much.
